### ISSUE TITLE
Incorrect Packed Results

### ISSUE THREAD

**Issue by SBCV** [Stwend/MeshroomTools#5]
Addon Version:  commit 0b0f0811397a46207a3442d346506a953e8cf275 ( i.e. `Fix for Issue #4`)
Blender Version: 2.82a
Operating System: Windows 10

Incorrect packed results:

![79994325-19346580-84b6-11ea-97f4-f8e3ee378512](https://user-images.githubusercontent.com/19491335/80293371-1314e200-875f-11ea-8d6b-95ca0cdbf67d.jpg)

Original result:

![79994367-294c4500-84b6-11ea-9008-46dec1c057ea](https://user-images.githubusercontent.com/19491335/80293379-2031d100-875f-11ea-8faf-9130b39cbaaf.jpg)

**Comment by SBCV** [comment]
Tried to reproduce this under Ubuntu 18.04, but there Blender freezes when executing the packing step :(

**Comment by Stwend** [comment]
No worries, I finally succeeded in replicating the bug.
The following things happen when there is an active camera anywhere in the scene:
To avoid dependencies to Pillow or other image processing libraries, I render the texture sheet with an orthographic camera inside Blender.
The plugin creates the orthographic camera, hides all objects in the scene except for the sheet and renders.
The bug happens because the plugin doesn't specifically set its camera as the active one - if another camera happens to exist, it will use that one and ignore its own camera.

**Comment by SBCV** [comment]
While that commit fixed the problem described above, both textures still appear to be different (see below)
Packed result:
![packed](https://user-images.githubusercontent.com/19491335/80303154-b04b3700-87ae-11ea-8aa3-1e22b827113a.jpg)
Original result:
![original](https://user-images.githubusercontent.com/19491335/80303164-b8a37200-87ae-11ea-87c3-6f2e879630e9.jpg)
Compare for example the texture at the windows. The effect is more obvious in Blender, where you can swap the textures and examine the differences.
My first guess would be that this is caused by the rendering step described above.

**Comment by Stwend** [comment]
Ah yes, there seems to be tonemapping getting applied somewhere in the process. The compositor and sequencer are turned off during the sheet rendering, but maybe I didn't "lock" enough parameters. Does the scene have exposure or gamma settings that differ from the default?

**Comment by SBCV** [comment]
This is the blend file I've been using
[inital.zip](https://github.com/Stwend/MeshroomTools/files/4535405/inital.zip)
